site_name: Zynq-7000 Baremetal
#site_url: ''
#use_directory_urls: false

theme:
    name: readthedocs
    max_width: 2000
    navigation_depth: 5
    font: false
    features:
        - content.code.copy
        - content.code.annotate
    #name: windmill

extra_css: 
    - extra.css


nav:
    - General:
        - Purpose                : index.md 
        - Implementation         : impl.md 
      
    - Software:  
        - Loader                 : loader.md
        - Application Program    : app.md
        - Debug                  : debug.md
      
    - Hardware:  
        - Interrupt Controller   : gic.md
        - Memory Management Unit : mmu.md

    - Libraries:
        - MMR Headers            : mmr-headers.md
        - Peripheral             : peripheral-lib.md

    - Target Boards:
        - ZedBoard               : zed.md
        - AX7021                 : ax7021.md


extra_javascript:
    - js/mathjax.js
    - js/mathjax/tex-mml-chtml.js
    - js/wavedrom.min.js
    - js/wavedrom_loader.js
    - js/wavedrom.unpkg.js
    - js/wavedrom_skin_default.js


markdown_extensions:
    - toc:
        permalink: "🔗"
        baselevel: 1
    - pymdownx.arithmatex:
       generic: true    
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
    - search:
        lang: ru

    - glightbox
    #- markdownwavedrom
